name: weightloss
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Theme and UI
  google_fonts: ^6.2.1
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^14.2.7
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # JSON Handling
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - lib/data/mock/
    - assets/images/
    - assets/icons/
